apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crpc-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  tls:
    - secretName: crpc-ssl-secret
  rules:
  - http:
      paths:
      - path: /
	    pathType: Prefix
	    backend:
          service:
            name: crpcserver
            port:
              number: 50000